---
title: "Other_functions"
output: html_document
date: "2022-09-12"
---

```{r setup, include=FALSE}
library(librarian)

# Main libraries
librarian::shelf(mice, reshape2)

# Library to use Python with R
librarian::shelf(
  reticulate,
  # Multidimensional reduction method library
  FactoMineR,
  # Survival analysis
  survival,
  survminer,
  # Display a corrplot
  corrplot,
  # Save corrplot as svg
  svglite,
  # Display a Sankey diagram
  networkD3,
  htmlwidgets,
  forcats,
  stringr,
  # data table management
  tibble,
  dplyr
)
```

### Utility F-scores comparison WBCD
```{r}
vec <- c("Bare Nuclei", "Uniformity of Cell Shape", "Uniformity of Cell Size",
         "Bland Chromatin", "Clump Thickness", "Normal Nucleoli", "Marginal Adhesion",
         "Single Epithelial Cell Size", "Mitoses") 

results_synthpop <- read.csv("/Users/morgan/Tech/avatar-paper/datasets/results_df/WBCD_synthpop_f-score_variousSplit.csv", sep = ",")
results_synthpop <- results_synthpop %>%
  dplyr::select(-c(X))
results_original <- results_synthpop %>%
  filter(type=="Original")
results_original <- left_join(data.frame(feature = vec),    # Reorder data frame
                              results_original,
                              by = "feature")
#results_original$color = "#fd934d"

results_synthpop <- results_synthpop %>%
  filter(type=="Synthpop")
results_synthpop <- left_join(data.frame(feature = vec),    # Reorder data frame
                              results_synthpop,
                              by = "feature")
#results_synthpop$color = "#b03bd6"


results_ctgan <- read.csv("/Users/morgan/Tech/avatar-paper/datasets/results_df/WBCD_ctgan_f-score_variousSplit.csv", sep = ",")
results_ctgan <- results_ctgan %>%
  dplyr::select(-c(X))
results_ctgan <- results_ctgan %>%
  filter(type=="CTGAN")
results_ctgan <- left_join(data.frame(feature = vec),    # Reorder data frame
                           results_ctgan,
                           by = "feature")
#results_ctgan$color = "#4db7fd"

results_avatar <- read.csv("/Users/morgan/Tech/avatar-paper/datasets/results_df/WBCD_f-score_variousSplit.csv", sep = ",")
results_avatar <- results_avatar %>%
  filter(type=="Avatar")
results_avatar <- left_join(data.frame(feature = vec),    # Reorder data frame
                            results_avatar,
                            by = "feature")
#results_avatar$color = "#3bd6b0"

total_results <-rbind(results_original,results_avatar,results_synthpop,results_ctgan)
total_results$feature_f = factor(total_results$feature, levels=c("Bare Nuclei", "Uniformity of Cell Shape", "Uniformity of Cell Size",
                                                                 "Bland Chromatin", "Clump Thickness", "Normal Nucleoli", "Marginal Adhesion",
                                                                 "Single Epithelial Cell Size", "Mitoses") )
total_results$type_f = factor(total_results$type, levels=c('CTGAN', 'Synthpop', 'Avatar', 'Original'))
total_results$type_g = factor(total_results$type, levels=c('Original', 'Avatar', 'Synthpop', 'CTGAN'))

ggplot(total_results, aes(x = F.score, y = type_f, fill = type)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c('Original'="#fd934d",
                               'Avatar'="#3bd6b0",
                               'Synthpop'="#b03bd6" ,
                               'CTGAN'="#4db7fd"),
                    breaks=c('Original', 'Avatar', 'Synthpop', 'CTGAN')) +
  theme_bw() +
  ylab(NULL) +
  xlab("F scores") +
  #scale_fill_discrete(breaks=c('Original', 'Avatar', 'Synthpop', 'CTGAN')) +
  facet_grid(feature_f~.,switch = 'y') +
  
  theme(text = element_text(size = 16), strip.text.y.left = element_text(angle = 0))
```

